config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :categories
  resources :types

  root "bookmarks#index"

  get "cycle/categories", to: "categories#cycle"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :type
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :category, optional: true
  has_many :categories

  has_many :bookmarks, dependent: :destroy
end

app/models/type.rb
class Type < ApplicationRecord
       has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]

  def index
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new
    #Tipos y Categorias
    @categories = Category.all
    @types = Type.all

    #Categorias publicas
    @public_categories = Category.where("public is true")
    #respuesta
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
  end

  def edit
    @categories = Category.all
    @types = Type.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: "El marcador fue creado con éxito" }
        format.js {}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to root_path, notice: "El marcador fue editado con éxito" }
        format.js { @bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js { render :index }
      end
    end
  end

  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: "El marcador fue borrado con éxito" }
      format.js {}
    end
  end

  private
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    def bookmark_params
      params.require(:bookmark).permit(:url, :type_id, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def cycle
    categoria_principal = Category.where('category_id is null')
    cycle = categoria_principal.map{|category| {Categoria: category.name, Subcategoria: category.categories.map{|sub| sub.name}}}
    render json: cycle
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :public, :category_id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  def index
    @types = Type.all

    # @chartkick = Bookmark.group(:type).count
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @type = Type.new
  end

  def edit
  end

  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_type
      @type = Type.find(params[:id])
    end

    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: @bookmark, remote: true, data: {confirm: "¿Deseas crear este marcador?"}, class: "form-inline text-white text-center" ) do |form| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field mx-2">
    <%= form.label "Url de la página web" %>
    <%= form.text_field :url%>
  </div>
  <div class="field mx-2">
    <%= form.label "Tipo de archivo" %>
    <%= form.collection_select :type_id, @types, :id, :name, prompt: "Selecciona..."%>
  </div>
  <div class="field mx-2">
    <%= form.label "Categoria del marcador" %>
    <%= form.collection_select :category_id, @categories, :id, :name, prompt: "Selecciona..."%>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-light' %>
  </div>
<% end %>

app/views/bookmarks/create.js.erb
$('#table').append(`
       <tr id=bookmark_<%= @bookmark.id %> >
              <td><%= @bookmark.url %></td>
              <td><%= @bookmark.category.name %></td>
              <td><%= @bookmark.type.name %></td>
              <td><%= link_to 'Ver', @bookmark %></td>
              <td><%= link_to 'Editar', edit_bookmark_path(@bookmark) %></td>
              <td><%= link_to 'Eliminar', @bookmark, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
       </tr>
`)

app/views/bookmarks/destroy.js.erb
$('#bookmark_<%= @bookmark.id %>').remove();

app/views/bookmarks/edit.html.erb
<h1 class="text-center my-3">Editar bookmark</h1>

<div class="bg-warning text-center">
<%= render "form", bookmark: @bookmark %>
<%= link_to "Volver atras", root_path, class: "btn" %>
</div>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="bg-warning py-4 px-5 text-center">
  <h4 class="my-5 text-dark">Crear un nuevo marcador</h4>
  <%= render "form" %>
</div>

<h1 class="text-center my-5">Bookmarks</h1>

<table class="table table-bordered table-secondary">
  <thead class="bg-warning text-dark">
    <tr>
      <th>Url</th>
      <th>Category</th>
      <th>Type</th>
      <th colspan="4" class="text-center">Opciones</th>
    </tr>
  </thead>
  <tbody id="table">
    <% @bookmarks.each do |bookmark| %>
    <% if @public_categories.include?(bookmark.category) || @public_categories.include?(bookmark.category.category_id) %>
      <tr id=bookmark_<%= bookmark.id %> >
        <td><%= bookmark.url %></td>
        <td><%= bookmark.category.name %></td>
        <td><%= bookmark.type.name %></td>
        <td><%= link_to 'Ver', bookmark %></td>
        <td><%= link_to 'Editar', edit_bookmark_path(bookmark.id)%></td>
        <td><%= link_to 'Eliminar', bookmark, method: :delete, data: { confirm: '¿Estás seguro que deseas eliminarlo?' }, remote: true %></td>
      </tr>
    <%end%>
    <% end %>
  </tbody>
</table>

<%= link_to "Editar categorias", categories_path, class: "btn btn-warning" %>
<%= link_to "Editar tipos", types_path, class: "btn btn-warning"  %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>


<div class="text-center bg-warning">
  <p>
    <strong>Url:</strong>
    <%= @bookmark.url %>
  </p>

  <p>
    <strong>Tipo</strong>
    <%= @bookmark.type.name %>
  </p>

  <p>
    <strong>Categoria</strong>
    <%= @bookmark.category.name %>
  </p>

  <%= link_to 'Edit', edit_bookmark_path(@bookmark), class: "btn" %> |
  <%= link_to 'Back', bookmarks_path, class: "btn" %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombe de la categoria" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :public, "¿La categoria es publica?" %>
    <%= form.check_box :public %>
  </div>

  <div class="field">
    <%= form.label :category_id, "¿La categoria pertene a alguna otra? Si ese es el caso, escribe el id de la categoria principal." %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit 'submit', class: "btn btn-light" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center my-4">Editar categoria</h1>

<div class="bg-warning text-dark container">
       <%= render 'form', category: @category %>

       <%= link_to 'Volver atras', categories_path, class: "btn" %>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center my-5">Categorias</h1>

<table class="table table-bordered table-secondary">
  <thead class="bg-warning text-dark">
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Publica</th>
      <th>Tipo de categoria</th>
      <th colspan="4" class="text-center">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td> <%= category.id %> </td>
        <td><%= category.name %></td>
        <td><%= category.public %></td>
        <% if category.category_id.nil? %>
        <td>Principal</td>
        <%else%>
        <td>Subcategoria</td>
        <%end%>
        <td><%= link_to 'Ver', category %></td>
        <td><%= link_to 'Editar', edit_category_path(category) %></td>
        <td><%= link_to 'Eliminar', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Atras", root_path, class: "btn btn-warning" %>
<%= link_to 'Crear una nueva categoria', new_category_path, class: "btn btn-warning" %>

app/views/categories/new.html.erb
<h1 class="text-center my-4">Crear nueva categoria</h1>
<div class="bg-warning text-dark container">
<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, class: "btn" %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="bg-warning text-dark text-center">
  <p>
    <strong>Name:</strong>
    <%= @category.name %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= @category.public %>
  </p>

  <% if @category.category.nil? %>
  <p>
    <strong>Categoria</strong>
    Principal
  </p>
  <% else %>
  <p>
    <strong>Categoria</strong>
    <%= @category.category.name %>
  </p>
  <%end%>

  <%= link_to 'Edit', edit_category_path(@category), class: "btn" %> |
  <%= link_to 'Back', categories_path, class: "btn" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marcadores</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombre del tipo" %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "submit", class:"btn" %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1 class="text-center my-4">Editar tipo</h1>

<div class="container bg-warning">
       <%= render 'form', type: @type %>

       <%= link_to 'Show', @type, class: "btn" %> |
       <%= link_to 'Back', types_path, class: "btn" %>
</div>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center my-5">Tipos de Archivos</h1>

<table class="table table-bordered table-secondary">
  <thead class="bg-warning text-dark">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="5" class="text-dark">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td> <%= type.id %> </td>
        <td><%= type.name %></td>
        <td><%= link_to "Ver", type %></td>
        <td><%= link_to 'Editar', edit_type_path(type) %></td>
        <td><%= link_to 'Eliminar', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3 class="text-center my-4">Grafico de marcadores</h3>
<%= pie_chart @bookmarks.group(:type_id).count %>

<%= link_to "Volver atras", root_path, class: "btn btn-warning" %>
<%= link_to 'Crear nuevo tipo', new_type_path, class: "btn btn-warning" %>

app/views/types/new.html.erb
<h1 class="text-center my-4">Crear nuevo tipo</h1>

<div class="container text-white bg-warning">
       <%= render 'form', type: @type %>

       <%= link_to 'Back', types_path, class: "btn" %>
</div>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<div class="bg-warning text-dark text-center">
  <p>
    <strong>Name:</strong>
    <%= @type.name %>
  </p>

  <%= link_to 'Edit', edit_type_path(@type), class: "btn" %> |
  <%= link_to 'Back', types_path, class: "btn" %>
</div>